### ISSUE TITLE
Notes on Section 2

### ISSUE THREAD

**Issue by b5** [qri-io/papers#7]
> In fact, Structure is abstracted in such a way that it contains nothing about meaning. If the values of a Data file change, the Structure can remain the same; if multiple Data objects anywhere on an IPFS network all have the same structure, the Structure object can remain the same. This is true even if the Data objects are about entirely different things. As will become more clear below, this is part of the fundamental insight that makes deterministic querying possible.

This is true, but it's important to note that `structure` comes in two forms, _concrete_ & _abstract_.  The `dataset` object references a concrete structure, which allows us to add things filed names, descriptions etc. Users need this data to know how to use the dataset, but obviously it doesn't have the nice hash-collision property. Thankfully, It's always possible to calculate the abstract version of a structure for a given structure, concrete or abstract, which gives us the hash-collidable form.

It must be true that
```go
structure.Abstract() == structure.Abstract().Abstract()
```

Current Code:
https://github.com/qri-io/dataset/blob/master/structure.go#L39

-- -- 

> Finally, if the Structure changes, the Data necessarily changes as well:

Along the same lines, it's not true that structure changes necessitate dataset changes. Classic example is misclassification of a field's data type. In that case it's possible to update the structure without changing the underlying data. (In practice this'll happen a lot as people mess with names or whatever). The present illustration is, however, a great example of a _schema migration_ that would modify both data and structure.

-- --

Beyond that, looks great! Thanks!

**Comment by b5** [comment]
Doing issue housekeeping, closing due to age. also, :wave: @mhucka!

**Comment by mhucka** [comment]
Oh hey @b5 :-). Errrm, I've lost track of this, rather obviously. My sincere apologies. Since it's closed, I assume you and the team have moved on, but if not, let me know and I'll try to reconstruct the train of thought.

**Comment by b5** [comment]
Oh no no this is great. No need to do work here. just wanted to say hello 😄
